
const funny_quotes = [
    "I'm not lazy, I'm on energy-saving mode.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not clumsy, it's just the floor hates me, the tables and chairs are bullies, and the walls get in my way.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not weird, I'm limited edition.",
    "I'm not a morning person. I'm a coffee person.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
    "I'm not lazy, I'm on energy-saving mode.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
    "I'm not lazy, I'm on energy-saving mode.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
    "I'm not lazy, I'm on energy-saving mode.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
    "I'm not lazy, I'm on energy-saving mode.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
    "I'm not lazy, I'm on energy-saving mode.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
    "I'm not lazy, I'm on energy-saving mode.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
    "I'm not lazy, I'm on energy-saving mode.",
    "I'm not a complete idiot, some parts are missing.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "I'm not short, I'm just more down to earth than most people.",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I'm not shy, I'm just conserving my awesomeness to avoid depletion.",
    "I'm not old, I'm a classic.",
    "I'm not late, everyone else is just early.",
    "I'm not fat, I'm just easy to see.",
    "I'm not ignoring you. I'm just prioritizing my time in a way that doesn't involve you.",
    "I'm not weird, I'm a limited edition.",
    "I'm not clumsy, I'm just allergic to gravity.",
]



function generateRandomQuote() {
    const quote = funny_quotes[Math.floor(Math.random() * funny_quotes.length)];
    document.getElementById("quote").innerHTML = quote;
}